set FAOCOUNTRY
/
'Afghanistan'
'Albania'
'Algeria'
'American Samoa'
'Andorra'
'Angola'
'Anguilla'
'Antigua and Barbuda'
'Argentina'
'Armenia'
'Aruba'
'Australia'
'Austria'
'Azerbaijan'
'Bahamas'
'Bahrain'
'Bangladesh'
'Barbados'
'Belarus'
'Belgium'
'Belize'
'Benin'
'Bhutan'
'Bolivia (Plurinational State of)'
'Bosnia and Herzegovina'
'Botswana'
'Brazil'
'British Indian Ocean Territory'
'British Virgin Islands'
'Brunei Darussalam'
'Bulgaria'
'Burkina Faso'
'Burundi'
"Côte d'Ivoire"
'Cabo Verde'
'Cambodia'
'Cameroon'
'Canada'
'Cape Verde'
'Cayman Islands'
'Central African Republic'
'Chad'
'Chile'
'China'
'China, Hong Kong SAR'
'China, Macao SAR'
'China, Taiwan Province of'
'Christmas Island'
'Cocos (Keeling) Islands'
'Colombia'
'Comoros'
'Congo'
'Cook Islands'
'Costa Rica'
'Croatia'
'Cuba'
'Curacao '
'Cyprus'
'Czechia'
'Czech Republic'
"Democratic People's Republic of Korea"
'Democratic Republic of the Congo'
'Denmark'
'Djibouti'
'Dominica'
'Dominican Republic'
'Ecuador'
'Egypt'
'El Salvador'
'Equatorial Guinea'
'Eritrea'
'Estonia'
'Eswatini'
'Ethiopia'
'Falkland Islands (Malvinas)'
'Faroe Islands'
'Fiji'
'Finland'
'Flores'
'France'
'French Guiana'
'French Polynesia'
'Gabon'
'Gambia'
'Georgia'
'Germany'
'Ghana'
'Gibraltar'
'Greece'
'Greenland'
'Grenada'
'Guadeloupe'
'Guatemala'
'Guinea'
'Guinea-Bissau'
'Guyana'
'Haiti'
'Honduras'
'Hungary'
'Iceland'
'India'
'Indonesia'
'Iran (Islamic Republic of)'
'Iraq'
'Ireland'
'Israel'
'Italy'
'Jamaica'
'Japan'
'Jordan'
'Kazakhstan'
'Kenya'
'Kiribati'
'Kuwait'
'Kyrgyzstan'
"Lao People's Democratic Republic"
'Latvia'
'Lebanon'
'Lesotho'
'Liberia'
'Libya'
'Liechtenstein'
'Lithuania'
'Lombok'
'Luxembourg'
'Madagascar'
'Malawi'
'Malaysia'
'Maldives'
'Mali'
'Malta'
'Marshall Islands'
'Martinique'
'Mauritania'
'Mauritius'
'Mayotte'
'Melanesia'
'Mexico'
'Micronesia (Federated States of)'
'Monaco'
'Mongolia'
'Montenegro'
'Montserrat'
'Morocco'
'Mozambique'
'Myanmar'
'Namibia'
'Nauru'
'Nepal'
'Netherlands'
'New Caledonia'
'New Guinea'
'New Zealand'
'Nicaragua'
'Niger'
'Nigeria'
'Niue'
'Norfolk Island'
'North Macedonia'
'Northern Mariana Islands'
'Norway'
'Oman'
'Pakistan'
'Palau'
'Palestine'
'Panama'
'Papua New Guinea'
'Paraguay'
'Peru'
'Philippines'
'Pitcairn Islands'
'Poland'
'Portugal'
'Puerto Rico'
'Qatar'
'Réunion'
'Republic of Korea'
'Republic of Moldova'
'Romania'
'Russia'
'Russian Federation'
'Rwanda'
'Saint Helena, Ascension and Tristan da Cunha'
'Saint Kitts and Nevis'
'Saint Lucia'
'Saint Pierre and Miquelon'
'Saint Vincent and the Grenadines'
'Saint-Martin (French Part)'
'Samoa'
'San Marino'
'Sao Tome and Principe'
'Saudi Arabia'
'Senegal'
'Serbia'
'Seychelles'
'Sierra Leone'
'Singapore'
'Slovakia'
'Slovenia'
'Solomon Islands'
'Somalia'
'South Africa'
'South Sudan'
'Spain'
'Sri Lanka'
'Sudan'
'Sulawesi'
'Sumbawa'
'Suriname'
'Swaziland'
'Sweden'
'Switzerland'
'Syrian Arab Republic'
'Taiwan'
'Tajikistan'
'Tasmania'
'Thailand'
'The former Yugoslav Republic of Macedonia'
'Timor'
'Timor-Leste'
'Togo'
'Tokelau'
'Tonga'
'Trinidad and Tobago'
'Tunisia'
'Turkey'
'Turkmenistan'
'Turks and Caicos Islands'
'Tuvalu'
'Uganda'
'Ukraine'
'United Arab Emirates'
'United Kingdom'
'United Republic of Tanzania'
'United States'
'Uruguay'
'Uzbekistan'
'Vanuatu'
'Vatican City'
'Venezuela (Bolivarian Republic of)'
'Viet Nam'
'Wake Island'
'Wallis and Futuna Islands'
'Yemen'
'Zambia'
'Zimbabwe'
'ROW'
'Rest of Africa'
'Rest of Asia'
'Rest of Europe'
'Rest of North America'
'Rest of Central America'
'Rest of South America'
'Rest of Oceania'/;

set FAOREGION
/
'Asia'
'Europe'
'Africa'
'North America'
'Central America'
'South America'
'Oceania'
/;


set     FAOAsia(FAOCOUNTRY)
        FAOEurope(FAOCOUNTRY)
        FAOAfrica(FAOCOUNTRY)
        FAONAmerica(FAOCOUNTRY)
        FAOCAmerica(FAOCOUNTRY)
        FAOSAmerica(FAOCOUNTRY)
        FAOOceania(FAOCOUNTRY)
        ROAfrica(FAOCOUNTRY)
        ROAsia(FAOCOUNTRY)
        ROEurope(FAOCOUNTRY)
        RONAmerica(FAOCOUNTRY)
        ROCAmerica(FAOCOUNTRY)
        ROSAmerica(FAOCOUNTRY)
        ROOceania(FAOCOUNTRY)
        ROW(FAOCOUNTRY)
        c(FAOCOUNTRY)

FAOAsia(FAOCOUNTRY) /
"Afghanistan" ,
"Armenia" ,
"Azerbaijan" ,
"Bahrain" ,
"Bangladesh" ,
"Bhutan" ,
"Brunei Darussalam" ,
"Cambodia" ,
"China" ,
"China, Macao SAR" ,
"China, Taiwan Province of" ,
"China, Hong Kong SAR" ,
"Taiwan" ,
"Timor-Leste" ,
"India" ,
"Indonesia" ,
"Iran (Islamic Republic of)" ,
"Iraq" ,
"Israel" ,
"Palestine" ,
"Japan" ,
"Jordan" ,
"Kazakhstan" ,
"Kuwait" ,
"Kyrgyzstan" ,
"Lao People's Democratic Republic" ,
"Lebanon" ,
"Malaysia" ,
"Maldives" ,
"Mongolia" ,
"Myanmar" ,
"Nepal" ,
"Northern Mariana Islands" ,
"Republic of Korea" ,
"Oman" ,
"Pakistan" ,
"Philippines" ,
"Qatar" ,
"Russian Federation" ,
"Saudi Arabia" ,
"Singapore" ,
"Democratic People's Republic of Korea" ,
"Sri Lanka" ,
"Syrian Arab Republic" ,
"Tajikistan" ,
"Thailand" ,
"Turkey" ,
"Turkmenistan" ,
"United Arab Emirates" ,
"Uzbekistan" ,
"Viet Nam" ,
"Yemen"
/

FAOEurope(FAOCOUNTRY) /
"Albania" ,
"Andorra" ,
"Austria" ,
"Belarus" ,
"Belgium" ,
"Bosnia and Herzegovina" ,
"Bulgaria" ,
"Croatia" ,
"Cyprus" ,
"Czech Republic" ,
"Denmark" ,
"Estonia" ,
"Faroe Islands" ,
"Finland" ,
"France" ,
"Gibraltar" ,
"Greenland" ,
"Germany" ,
"Georgia" ,
"Greece" ,
"Hungary" ,
"Iceland" ,
"Ireland" ,
"Italy" ,
"Latvia" ,
"Liechtenstein" ,
"Lithuania" ,
"Luxembourg" ,
"The former Yugoslav Republic of Macedonia" ,
"Malta" ,
"Republic of Moldova" ,
"Monaco" ,
"Montenegro" ,
"Netherlands" ,
"Norway" ,
"Poland" ,
"Portugal" ,
"Romania" ,
"Russia" ,
"San Marino" ,
"Serbia" ,
"Slovakia" ,
"Slovenia" ,
"Spain" ,
"Sweden" ,
"Switzerland" ,
"Ukraine" ,
"United Kingdom" ,
"Vatican City"
/

FAOAfrica(FAOCOUNTRY) /
"Algeria" ,
"Angola" ,
"Benin" ,
"Botswana" ,
"Burkina Faso" ,
"Burundi" ,
"Cabo Verde" ,
"Cameroon" ,
"Cape Verde" ,
"Chad" ,
"Central African Republic" ,
"Comoros" ,
"Congo" ,
"Democratic Republic of the Congo" ,
"Côte d'Ivoire" ,
"Djibouti" ,
"Egypt" ,
"Equatorial Guinea" ,
"Eritrea" ,
"Ethiopia" ,
"Gabon" ,
"Gambia" ,
"Ghana" ,
"Guinea" ,
"Guinea-Bissau" ,
"Kenya" ,
"Lesotho" ,
"Liberia" ,
"Libya" ,
"Madagascar" ,
"Malawi" ,
"Mali" ,
"Mauritania" ,
"Mauritius" ,
"Morocco" ,
"Mozambique" ,
"Mayotte" ,
"Namibia" ,
"Niger" ,
"Nigeria" ,
"Rwanda" ,
"Réunion" ,
"Sao Tome and Principe" ,
"Senegal" ,
"Seychelles" ,
"Sierra Leone" ,
"Somalia" ,
"South Africa" ,
"South Sudan" ,
"Sudan" ,
"Swaziland" ,
"United Republic of Tanzania" ,
"Togo" ,
"Tunisia" ,
"Uganda" ,
"Zambia" ,
"Zimbabwe"
/

FAONAmerica(FAOCOUNTRY) /
"Canada" ,
"Mexico" ,
"United States" ,
"Saint Pierre and Miquelon" ,
"Anguilla"
/


FAOCAmerica(FAOCOUNTRY) /
"Antigua and Barbuda" ,
"Bahamas" ,
"Barbados" ,
"Belize" ,
"British Virgin Islands" ,
"Curacao" ,
"Cayman Islands" ,
"Costa Rica" ,
"Cuba" ,
"Dominica" ,
"Dominican Republic" ,
"El Salvador" ,
"Grenada" ,
"Guatemala" ,
"Guadeloupe" ,
"Haiti" ,
"Honduras" ,
"Jamaica" ,
"Martinique" ,
"Montserrat" ,
"Nicaragua" ,
"Panama" ,
"Puerto Rico" ,
"Saint Kitts and Nevis" ,
"Saint Lucia" ,
"Saint Vincent and the Grenadines" ,
"Saint-Martin (French Part)" ,
"Trinidad and Tobago" ,
"Turks and Caicos Islands"
/

FAOSAmerica(FAOCOUNTRY) /
"Aruba" ,
"Argentina" ,
"Bolivia (Plurinational State of)" ,
"Brazil" ,
"Chile" ,
"Colombia" ,
"Falkland Islands (Malvinas)" ,
"Ecuador" ,
"French Guiana" ,
"Guyana" ,
"Paraguay" ,
"Peru" ,
"Suriname" ,
"Uruguay" ,
"Venezuela (Bolivarian Republic of)"
/


FAOOceania(FAOCOUNTRY) /
"Australia" ,
"Fiji" ,
"Papua New Guinea" ,
"Solomon Islands" ,
"Vanuatu" ,
"Kiribati" ,
"Marshall Islands" ,
"French Polynesia" ,
"Micronesia (Federated States of)" ,
"Nauru" ,
"Palau" ,
"Samoa" ,
"Tonga" ,
"Tuvalu" ,
"Flores" ,
"Lombok" ,
"Melanesia" ,
"New Caledonia" ,
"New Guinea" ,
"New Zealand" ,
"Sulawesi" ,
"Sumbawa" ,
"Tasmania" ,
"Timor" ,
"Cook Islands" ,
"Wallis and Futuna Islands" ,
"Norfolk Island" ,
"Niue" ,
"Christmas Island" ,
"American Samoa" ,
"British Indian Ocean Territory" ,
"Cocos (Keeling) Islands" ,
"Pitcairn Islands" ,
"Saint Helena, Ascension and Tristan da Cunha" ,
"Tokelau" ,
"Wake Island"
/




Set FAOC2R
/
'Afghanistan' .'Asia'
'Albania' .'Europe'
'Algeria' .'Africa'
'American Samoa' .'Oceania'
'Andorra' .'Europe'
'Angola' .'Africa'
'Anguilla' .'North America'
'Antigua and Barbuda' .'Central America'
'Argentina' .'South America'
'Armenia' .'Asia'
'Aruba' .'South America'
'Australia' .'Oceania'
'Austria' .'Europe'
'Azerbaijan' .'Asia'
'Bahamas' .'Central America'
'Bahrain' .'Asia'
'Bangladesh' .'Asia'
'Barbados' .'Central America'
'Belarus' .'Europe'
'Belgium' .'Europe'
'Belize' .'Central America'
'Benin' .'Africa'
'Bhutan' .'Asia'
'Bolivia (Plurinational State of)' .'South America'
'Bosnia and Herzegovina' .'Europe'
'Botswana' .'Africa'
'Brazil' .'South America'
'British Indian Ocean Territory' .'Oceania'
'British Virgin Islands' .'Central America'
'Brunei Darussalam' .'Asia'
'Bulgaria' .'Europe'
'Burkina Faso' .'Africa'
'Burundi' .'Africa'
"Côte d'Ivoire" .'Africa'
'Cabo Verde' .'Africa'
'Cambodia' .'Asia'
'Cameroon' .'Africa'
'Canada' .'North America'
'Cape Verde' .'Africa'
'Cayman Islands' .'Central America'
'Central African Republic' .'Africa'
'Chad' .'Africa'
'Chile' .'South America'
'China' .'Asia'
'China, Hong Kong SAR' .'Asia'
'China, Macao SAR' .'Asia'
'China, Taiwan Province of' .'Asia'
'Christmas Island' .'Oceania'
'Cocos (Keeling) Islands' .'Oceania'
'Colombia' .'South America'
'Comoros' .'Africa'
'Congo' .'Africa'
'Cook Islands' .'Oceania'
'Costa Rica' .'Central America'
'Croatia' .'Europe'
'Cuba' .'Central America'
'Curacao ' .'Central America'
'Cyprus' .'Europe'
'Czechia' .'Europe'
'Czech Republic' .'Europe'
"Democratic People's Republic of Korea" .'Asia'
'Democratic Republic of the Congo' .'Africa'
'Denmark' .'Europe'
'Djibouti' .'Africa'
'Dominica' .'Central America'
'Dominican Republic' .'Central America'
'Ecuador' .'South America'
'Egypt' .'Africa'
'El Salvador' .'Central America'
'Equatorial Guinea' .'Africa'
'Eritrea' .'Africa'
'Estonia' .'Europe'
'Eswatini' .'Africa'
'Ethiopia' .'Africa'
'Falkland Islands (Malvinas)' .'South America'
'Faroe Islands' .'Europe'
'Fiji' .'Oceania'
'Finland' .'Europe'
'Flores' .'Oceania'
'France' .'Europe'
'French Guiana' .'South America'
'French Polynesia' .'Oceania'
'Gabon' .'Africa'
'Gambia' .'Africa'
'Georgia' .'Europe'
'Germany' .'Europe'
'Ghana' .'Africa'
'Gibraltar' .'Europe'
'Greece' .'Europe'
'Greenland' .'Europe'
'Grenada' .'Central America'
'Guadeloupe' .'Central America'
'Guatemala' .'Central America'
'Guinea' .'Africa'
'Guinea-Bissau' .'Africa'
'Guyana' .'South America'
'Haiti' .'Central America'
'Honduras' .'Central America'
'Hungary' .'Europe'
'Iceland' .'Europe'
'India' .'Asia'
'Indonesia' .'Asia'
'Iran (Islamic Republic of)' .'Asia'
'Iraq' .'Asia'
'Ireland' .'Europe'
'Israel' .'Asia'
'Italy' .'Europe'
'Jamaica' .'Central America'
'Japan' .'Asia'
'Jordan' .'Asia'
'Kazakhstan' .'Asia'
'Kenya' .'Africa'
'Kiribati' .'Oceania'
'Kuwait' .'Asia'
'Kyrgyzstan' .'Asia'
"Lao People's Democratic Republic" .'Asia'
'Latvia' .'Europe'
'Lebanon' .'Asia'
'Lesotho' .'Africa'
'Liberia' .'Africa'
'Libya' .'Africa'
'Liechtenstein' .'Europe'
'Lithuania' .'Europe'
'Lombok' .'Oceania'
'Luxembourg' .'Europe'
'Madagascar' .'Africa'
'Malawi' .'Africa'
'Malaysia' .'Asia'
'Maldives' .'Asia'
'Mali' .'Africa'
'Malta' .'Europe'
'Marshall Islands' .'Oceania'
'Martinique' .'Central America'
'Mauritania' .'Africa'
'Mauritius' .'Africa'
'Mayotte' .'Africa'
'Melanesia' .'Oceania'
'Mexico' .'North America'
'Micronesia (Federated States of)' .'Oceania'
'Monaco' .'Europe'
'Mongolia' .'Asia'
'Montenegro' .'Europe'
'Montserrat' .'Central America'
'Morocco' .'Africa'
'Mozambique' .'Africa'
'Myanmar' .'Asia'
'Namibia' .'Africa'
'Nauru' .'Oceania'
'Nepal' .'Asia'
'Netherlands' .'Europe'
'New Caledonia' .'Oceania'
'New Guinea' .'Oceania'
'New Zealand' .'Oceania'
'Nicaragua' .'Central America'
'Niger' .'Africa'
'Nigeria' .'Africa'
'Niue' .'Oceania'
'Norfolk Island' .'Oceania'
'North Macedonia' .'Europe'
'Northern Mariana Islands' .'Asia'
'Norway' .'Europe'
'Oman' .'Asia'
'Pakistan' .'Asia'
'Palau' .'Oceania'
'Palestine' .'Asia'
'Panama' .'Central America'
'Papua New Guinea' .'Oceania'
'Paraguay' .'South America'
'Peru' .'South America'
'Philippines' .'Asia'
'Pitcairn Islands' .'Oceania'
'Poland' .'Europe'
'Portugal' .'Europe'
'Puerto Rico' .'Central America'
'Qatar' .'Asia'
'Réunion' .'Africa'
'Republic of Korea' .'Asia'
'Republic of Moldova' .'Europe'
'Romania' .'Europe'
'Russia' .'Europe'
'Russian Federation' .'Asia'
'Rwanda' .'Africa'
'Saint Helena, Ascension and Tristan da Cunha' .'Oceania'
'Saint Kitts and Nevis' .'Central America'
'Saint Lucia' .'Central America'
'Saint Pierre and Miquelon' .'North America'
'Saint Vincent and the Grenadines' .'Central America'
'Saint-Martin (French Part)' .'Central America'
'Samoa' .'Oceania'
'San Marino' .'Europe'
'Sao Tome and Principe' .'Africa'
'Saudi Arabia' .'Asia'
'Senegal' .'Africa'
'Serbia' .'Europe'
'Seychelles' .'Africa'
'Sierra Leone' .'Africa'
'Singapore' .'Asia'
'Slovakia' .'Europe'
'Slovenia' .'Europe'
'Solomon Islands' .'Oceania'
'Somalia' .'Africa'
'South Africa' .'Africa'
'South Sudan' .'Africa'
'Spain' .'Europe'
'Sri Lanka' .'Asia'
'Sudan' .'Africa'
'Sulawesi' .'Oceania'
'Sumbawa' .'Oceania'
'Suriname' .'South America'
'Swaziland' .'Africa'
'Sweden' .'Europe'
'Switzerland' .'Europe'
'Syrian Arab Republic' .'Asia'
'Taiwan' .'Asia'
'Tajikistan' .'Asia'
'Tasmania' .'Oceania'
'Thailand' .'Asia'
'The former Yugoslav Republic of Macedonia' .'Europe'
'Timor' .'Oceania'
'Timor-Leste' .'Asia'
'Togo' .'Africa'
'Tokelau' .'Oceania'
'Tonga' .'Oceania'
'Trinidad and Tobago' .'Central America'
'Tunisia' .'Africa'
'Turkey' .'Asia'
'Turkmenistan' .'Asia'
'Turks and Caicos Islands' .'Central America'
'Tuvalu' .'Oceania'
'Uganda' .'Africa'
'Ukraine' .'Europe'
'United Arab Emirates' .'Asia'
'United Kingdom' .'Europe'
'United Republic of Tanzania' .'Africa'
'United States' .'North America'
'Uruguay' .'South America'
'Uzbekistan' .'Asia'
'Vanuatu' .'Oceania'
'Vatican City' .'Europe'
'Venezuela (Bolivarian Republic of)' .'South America'
'Viet Nam' .'Asia'
'Wake Island' .'Oceania'
'Wallis and Futuna Islands' .'Oceania'
'Yemen' .'Asia'
'Zambia' .'Africa'
'Zimbabwe' .'Africa'
'ROW' .'ROW'
'Rest of Africa' .'Africa'
'Rest of Asia' .'Asia'
'Rest of Europe' .'Europe'
'Rest of North America' .'North America'
'Rest of Central America' .'Central America'
'Rest of South America' .'South America'
'Rest of Oceania' .'Oceania'
/
;

